/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.apis.CoreApi
import com.betatel.esim.models.Error
import com.betatel.esim.models.GetCountriesResponse

class CoreApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CoreApi
        //val apiInstance = CoreApi()

        // to test getCountries
        should("test getCountries") {
            // uncomment below to test getCountries
            //val count : kotlin.Int = 56 // kotlin.Int | Number of items to return per page
            //val offset : kotlin.Int = 56 // kotlin.Int | Number of items to skip (for pagination)
            //val result : GetCountriesResponse = apiInstance.getCountries(count, offset)
            //result shouldBe ("TODO")
        }

    }
}
