/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.apis.ESIMRSPApi
import com.betatel.esim.models.Error
import com.betatel.esim.models.GetEUICCProfileResponse

class ESIMRSPApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ESIMRSPApi
        //val apiInstance = ESIMRSPApi()

        // to test getEUICCProfile
        should("test getEUICCProfile") {
            // uncomment below to test getEUICCProfile
            //val iccid : kotlin.String = 8910300000045681955 // kotlin.String | The ICCID of the eSIM (19-20 digits)
            //val result : GetEUICCProfileResponse = apiInstance.getEUICCProfile(iccid)
            //result shouldBe ("TODO")
        }

        // to test getQRCode
        should("test getQRCode") {
            // uncomment below to test getQRCode
            //val iccid : kotlin.String = 8910300000045681955 // kotlin.String | The ICCID of the eSIM (19-20 digits)
            //val result : java.io.File = apiInstance.getQRCode(iccid)
            //result shouldBe ("TODO")
        }

    }
}
