/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.apis.InventoryApi
import com.betatel.esim.models.ESIM
import com.betatel.esim.models.Error
import com.betatel.esim.models.GetESIMsResponse
import com.betatel.esim.models.GetInventoriesResponse

class InventoryApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InventoryApi
        //val apiInstance = InventoryApi()

        // to test getESIM
        should("test getESIM") {
            // uncomment below to test getESIM
            //val iccid : kotlin.String = 8910300000045681955 // kotlin.String | The ICCID of the eSIM (19-20 digits)
            //val result : ESIM = apiInstance.getESIM(iccid)
            //result shouldBe ("TODO")
        }

        // to test getESIMs
        should("test getESIMs") {
            // uncomment below to test getESIMs
            //val count : kotlin.Int = 56 // kotlin.Int | Number of items to return
            //val offset : kotlin.Int = 56 // kotlin.Int | Number of items to skip
            //val group : kotlin.Int = 56 // kotlin.Int | Filter by group ID (optional)
            //val inventory : kotlin.Int = 56 // kotlin.Int | Filter by inventory ID (optional)
            //val result : GetESIMsResponse = apiInstance.getESIMs(count, offset, group, inventory)
            //result shouldBe ("TODO")
        }

        // to test getInventories
        should("test getInventories") {
            // uncomment below to test getInventories
            //val count : kotlin.Int = 56 // kotlin.Int | Number of items to return
            //val offset : kotlin.Int = 56 // kotlin.Int | Number of items to skip
            //val company : kotlin.Int = 56 // kotlin.Int | Filter by company ID (optional)
            //val result : GetInventoriesResponse = apiInstance.getInventories(count, offset, company)
            //result shouldBe ("TODO")
        }

    }
}
