/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.apis.PackagesApi
import com.betatel.esim.models.CreatePackageRequest
import com.betatel.esim.models.CreatePackageResponse
import com.betatel.esim.models.Error
import com.betatel.esim.models.GetPackagesResponse
import com.betatel.esim.models.Package

class PackagesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PackagesApi
        //val apiInstance = PackagesApi()

        // to test activatePackage
        should("test activatePackage") {
            // uncomment below to test activatePackage
            //val id : kotlin.String = pkg_123456 // kotlin.String | Package ID to activate
            //val result : kotlin.Boolean = apiInstance.activatePackage(id)
            //result shouldBe ("TODO")
        }

        // to test createPackage
        should("test createPackage") {
            // uncomment below to test createPackage
            //val createPackageRequest : CreatePackageRequest =  // CreatePackageRequest | 
            //val result : CreatePackageResponse = apiInstance.createPackage(createPackageRequest)
            //result shouldBe ("TODO")
        }

        // to test getPackage
        should("test getPackage") {
            // uncomment below to test getPackage
            //val id : kotlin.String = pkg_123456 // kotlin.String | Package ID
            //val result : Package = apiInstance.getPackage(id)
            //result shouldBe ("TODO")
        }

        // to test getPackages
        should("test getPackages") {
            // uncomment below to test getPackages
            //val count : kotlin.Int = 56 // kotlin.Int | Number of items to return
            //val offset : kotlin.Int = 56 // kotlin.Int | Number of items to skip
            //val inventory : kotlin.Int = 56 // kotlin.Int | Filter by inventory ID
            //val packageTemplate : kotlin.Int = 56 // kotlin.Int | Filter by package template ID
            //val sim : kotlin.String = sim_example // kotlin.String | Filter by SIM ICCID
            //val status : kotlin.String = status_example // kotlin.String | Filter by package status
            //val result : GetPackagesResponse = apiInstance.getPackages(count, offset, inventory, packageTemplate, sim, status)
            //result shouldBe ("TODO")
        }

        // to test terminatePackage
        should("test terminatePackage") {
            // uncomment below to test terminatePackage
            //val id : kotlin.String = pkg_123456 // kotlin.String | Package ID to terminate
            //val result : kotlin.Boolean = apiInstance.terminatePackage(id)
            //result shouldBe ("TODO")
        }

    }
}
