/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.apis.PCRApi
import com.betatel.esim.models.CreatePackageTemplateRequest
import com.betatel.esim.models.CreatePackageTemplateResponse
import com.betatel.esim.models.Error
import com.betatel.esim.models.GetPackageTemplatesResponse
import com.betatel.esim.models.PackageTemplate

class PCRApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PCRApi
        //val apiInstance = PCRApi()

        // to test createPackageTemplate
        should("test createPackageTemplate") {
            // uncomment below to test createPackageTemplate
            //val createPackageTemplateRequest : CreatePackageTemplateRequest =  // CreatePackageTemplateRequest | 
            //val result : CreatePackageTemplateResponse = apiInstance.createPackageTemplate(createPackageTemplateRequest)
            //result shouldBe ("TODO")
        }

        // to test getPackageTemplate
        should("test getPackageTemplate") {
            // uncomment below to test getPackageTemplate
            //val id : kotlin.Int = 21145354 // kotlin.Int | Package template ID
            //val result : PackageTemplate = apiInstance.getPackageTemplate(id)
            //result shouldBe ("TODO")
        }

        // to test getPackageTemplates
        should("test getPackageTemplates") {
            // uncomment below to test getPackageTemplates
            //val count : kotlin.Int = 56 // kotlin.Int | Number of items to return
            //val offset : kotlin.Int = 56 // kotlin.Int | Number of items to skip
            //val inventory : kotlin.Int = 56 // kotlin.Int | Filter by inventory ID (optional)
            //val result : GetPackageTemplatesResponse = apiInstance.getPackageTemplates(count, offset, inventory)
            //result shouldBe ("TODO")
        }

    }
}
