/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.apis.PCRProfileApi
import com.betatel.esim.models.Error
import com.betatel.esim.models.GetPCRProfileResponse
import com.betatel.esim.models.ModifyPCRProfileRequest

class PCRProfileApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PCRProfileApi
        //val apiInstance = PCRProfileApi()

        // to test getPCRProfile
        should("test getPCRProfile") {
            // uncomment below to test getPCRProfile
            //val iccid : kotlin.String = 8910300000045681955 // kotlin.String | The ICCID of the SIM card (19-20 digits)
            //val result : GetPCRProfileResponse = apiInstance.getPCRProfile(iccid)
            //result shouldBe ("TODO")
        }

        // to test modifyPCRProfile
        should("test modifyPCRProfile") {
            // uncomment below to test modifyPCRProfile
            //val iccid : kotlin.String = 8910300000045681955 // kotlin.String | The ICCID of the SIM card (19-20 digits)
            //val modifyPCRProfileRequest : ModifyPCRProfileRequest = {"data":{"state":"ENABLED","active_throttling":"SPEED_1000_KBPS"}} // ModifyPCRProfileRequest | 
            //apiInstance.modifyPCRProfile(iccid, modifyPCRProfileRequest)
        }

    }
}
