/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.apis.SystemApi
import com.betatel.esim.models.Error
import com.betatel.esim.models.StatusResponse

class SystemApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemApi
        //val apiInstance = SystemApi()

        // to test getStatus
        should("test getStatus") {
            // uncomment below to test getStatus
            //val result : StatusResponse = apiInstance.getStatus()
            //result shouldBe ("TODO")
        }

    }
}
