/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.Country

class CountryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Country
        //val modelInstance = Country()

        // to test the property `name` - Full country name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `iso2` - ISO 3166-1 alpha-2 country code
        should("test iso2") {
            // uncomment below to test the property
            //modelInstance.iso2 shouldBe ("TODO")
        }

        // to test the property `iso3` - ISO 3166-1 alpha-3 country code
        should("test iso3") {
            // uncomment below to test the property
            //modelInstance.iso3 shouldBe ("TODO")
        }

    }
}
