/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.CreatePackageTemplateRequest
import com.betatel.esim.models.TimeAllowance

class CreatePackageTemplateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreatePackageTemplateRequest
        //val modelInstance = CreatePackageTemplateRequest()

        // to test the property `name` - Package template name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `supportedCountries` - Array of supported country ISO3 codes
        should("test supportedCountries") {
            // uncomment below to test the property
            //modelInstance.supportedCountries shouldBe ("TODO")
        }

        // to test the property `activationType` - Package activation type
        should("test activationType") {
            // uncomment below to test the property
            //modelInstance.activationType shouldBe ("TODO")
        }

        // to test the property `dataUsageAllowance` - Data allowance in bytes
        should("test dataUsageAllowance") {
            // uncomment below to test the property
            //modelInstance.dataUsageAllowance shouldBe ("TODO")
        }

        // to test the property `timeAllowance`
        should("test timeAllowance") {
            // uncomment below to test the property
            //modelInstance.timeAllowance shouldBe ("TODO")
        }

        // to test the property `activationTimeAllowance` - Time allowance for activation in seconds
        should("test activationTimeAllowance") {
            // uncomment below to test the property
            //modelInstance.activationTimeAllowance shouldBe ("TODO")
        }

        // to test the property `earliestAvailableDate` - Unix timestamp for earliest availability
        should("test earliestAvailableDate") {
            // uncomment below to test the property
            //modelInstance.earliestAvailableDate shouldBe ("TODO")
        }

        // to test the property `latestAvailableDate` - Unix timestamp for latest availability
        should("test latestAvailableDate") {
            // uncomment below to test the property
            //modelInstance.latestAvailableDate shouldBe ("TODO")
        }

        // to test the property `inventory` - Inventory ID to associate the template with
        should("test inventory") {
            // uncomment below to test the property
            //modelInstance.inventory shouldBe ("TODO")
        }

    }
}
