/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.CreatePackageTemplateResponse
import com.betatel.esim.models.TimeAllowance

class CreatePackageTemplateResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreatePackageTemplateResponse
        //val modelInstance = CreatePackageTemplateResponse()

        // to test the property `id` - Created package template ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - Package template name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `voiceUsageAllowance` - Voice allowance in minutes
        should("test voiceUsageAllowance") {
            // uncomment below to test the property
            //modelInstance.voiceUsageAllowance shouldBe ("TODO")
        }

        // to test the property `dataUsageAllowance` - Data allowance in bytes
        should("test dataUsageAllowance") {
            // uncomment below to test the property
            //modelInstance.dataUsageAllowance shouldBe ("TODO")
        }

        // to test the property `smsUsageAllowance` - SMS allowance count
        should("test smsUsageAllowance") {
            // uncomment below to test the property
            //modelInstance.smsUsageAllowance shouldBe ("TODO")
        }

        // to test the property `timeAllowance`
        should("test timeAllowance") {
            // uncomment below to test the property
            //modelInstance.timeAllowance shouldBe ("TODO")
        }

        // to test the property `activationTimeAllowance` - Time allowance for activation in seconds
        should("test activationTimeAllowance") {
            // uncomment below to test the property
            //modelInstance.activationTimeAllowance shouldBe ("TODO")
        }

    }
}
