/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.CreatePackageResponse
import com.betatel.esim.models.CreatePackageResponsePackageTemplate

class CreatePackageResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreatePackageResponse
        //val modelInstance = CreatePackageResponse()

        // to test the property `id` - Created package ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `sim` - SIM ICCID
        should("test sim") {
            // uncomment below to test the property
            //modelInstance.sim shouldBe ("TODO")
        }

        // to test the property `createdDate` - Unix timestamp of package creation
        should("test createdDate") {
            // uncomment below to test the property
            //modelInstance.createdDate shouldBe ("TODO")
        }

        // to test the property `expiryDate` - Unix timestamp of package expiry
        should("test expiryDate") {
            // uncomment below to test the property
            //modelInstance.expiryDate shouldBe ("TODO")
        }

        // to test the property `activatedDate` - Unix timestamp when package was activated (0 if not activated)
        should("test activatedDate") {
            // uncomment below to test the property
            //modelInstance.activatedDate shouldBe ("TODO")
        }

        // to test the property `terminatedDate` - Unix timestamp when package was terminated (0 if not terminated)
        should("test terminatedDate") {
            // uncomment below to test the property
            //modelInstance.terminatedDate shouldBe ("TODO")
        }

        // to test the property `windowActivationStart` - Unix timestamp of activation window start
        should("test windowActivationStart") {
            // uncomment below to test the property
            //modelInstance.windowActivationStart shouldBe ("TODO")
        }

        // to test the property `windowActivationEnd` - Unix timestamp of activation window end
        should("test windowActivationEnd") {
            // uncomment below to test the property
            //modelInstance.windowActivationEnd shouldBe ("TODO")
        }

        // to test the property `status` - Current package status
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `voiceUsageRemaining` - Remaining voice minutes
        should("test voiceUsageRemaining") {
            // uncomment below to test the property
            //modelInstance.voiceUsageRemaining shouldBe ("TODO")
        }

        // to test the property `dataUsageRemaining` - Remaining data in bytes
        should("test dataUsageRemaining") {
            // uncomment below to test the property
            //modelInstance.dataUsageRemaining shouldBe ("TODO")
        }

        // to test the property `smsUsageRemaining` - Remaining SMS count
        should("test smsUsageRemaining") {
            // uncomment below to test the property
            //modelInstance.smsUsageRemaining shouldBe ("TODO")
        }

        // to test the property `timeAllowance` - Time allowance in seconds
        should("test timeAllowance") {
            // uncomment below to test the property
            //modelInstance.timeAllowance shouldBe ("TODO")
        }

        // to test the property `packageTemplate`
        should("test packageTemplate") {
            // uncomment below to test the property
            //modelInstance.packageTemplate shouldBe ("TODO")
        }

        // to test the property `apn` - Access Point Name
        should("test apn") {
            // uncomment below to test the property
            //modelInstance.apn shouldBe ("TODO")
        }

    }
}
