/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.CreatePackageRequest

class CreatePackageRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreatePackageRequest
        //val modelInstance = CreatePackageRequest()

        // to test the property `sim` - The ICCID of the SIM card
        should("test sim") {
            // uncomment below to test the property
            //modelInstance.sim shouldBe ("TODO")
        }

        // to test the property `packageTemplate` - The package template ID
        should("test packageTemplate") {
            // uncomment below to test the property
            //modelInstance.packageTemplate shouldBe ("TODO")
        }

        // to test the property `timeAllowance` - Optional time allowance in seconds
        should("test timeAllowance") {
            // uncomment below to test the property
            //modelInstance.timeAllowance shouldBe ("TODO")
        }

    }
}
