/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.DataProfile

class DataProfileTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DataProfile
        //val modelInstance = DataProfile()

        // to test the property `state` - Current state of the data profile
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `activeThrottling` - Current throttling speed configuration
        should("test activeThrottling") {
            // uncomment below to test the property
            //modelInstance.activeThrottling shouldBe ("TODO")
        }

    }
}
