/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.ESIM
import com.betatel.esim.models.ESIMCompany
import com.betatel.esim.models.ESIMGroup
import com.betatel.esim.models.ESIMInventory
import com.betatel.esim.models.IMSI

class ESIMTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ESIM
        //val modelInstance = ESIM()

        // to test the property `iccid` - Integrated Circuit Card Identifier
        should("test iccid") {
            // uncomment below to test the property
            //modelInstance.iccid shouldBe ("TODO")
        }

        // to test the property `simStatus` - Current status of the SIM
        should("test simStatus") {
            // uncomment below to test the property
            //modelInstance.simStatus shouldBe ("TODO")
        }

        // to test the property `group`
        should("test group") {
            // uncomment below to test the property
            //modelInstance.group shouldBe ("TODO")
        }

        // to test the property `inventory`
        should("test inventory") {
            // uncomment below to test the property
            //modelInstance.inventory shouldBe ("TODO")
        }

        // to test the property `company`
        should("test company") {
            // uncomment below to test the property
            //modelInstance.company shouldBe ("TODO")
        }

        // to test the property `provisionedDate` - Unix timestamp when SIM was provisioned
        should("test provisionedDate") {
            // uncomment below to test the property
            //modelInstance.provisionedDate shouldBe ("TODO")
        }

        // to test the property `terminatedDate` - Unix timestamp when SIM was terminated (0 if active)
        should("test terminatedDate") {
            // uncomment below to test the property
            //modelInstance.terminatedDate shouldBe ("TODO")
        }

        // to test the property `imsis` - List of associated IMSIs
        should("test imsis") {
            // uncomment below to test the property
            //modelInstance.imsis shouldBe ("TODO")
        }

        // to test the property `mappedImsi` - Currently mapped IMSI
        should("test mappedImsi") {
            // uncomment below to test the property
            //modelInstance.mappedImsi shouldBe ("TODO")
        }

    }
}
