/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.GetCountriesResponse
import com.betatel.esim.models.Country

class GetCountriesResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetCountriesResponse
        //val modelInstance = GetCountriesResponse()

        // to test the property `total` - Total number of countries available in the system
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `count` - Number of countries returned in this response
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `offset` - Number of countries skipped
        should("test offset") {
            // uncomment below to test the property
            //modelInstance.offset shouldBe ("TODO")
        }

        // to test the property `countries` - Array of country objects
        should("test countries") {
            // uncomment below to test the property
            //modelInstance.countries shouldBe ("TODO")
        }

    }
}
