/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.GetESIMsResponse
import com.betatel.esim.models.ESIM

class GetESIMsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetESIMsResponse
        //val modelInstance = GetESIMsResponse()

        // to test the property `total` - Total number of eSIMs available in the system
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `count` - Number of eSIMs returned in this response
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `offset` - Number of eSIMs skipped
        should("test offset") {
            // uncomment below to test the property
            //modelInstance.offset shouldBe ("TODO")
        }

        // to test the property `sims` - Array of eSIM objects
        should("test sims") {
            // uncomment below to test the property
            //modelInstance.sims shouldBe ("TODO")
        }

    }
}
