/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.GetEUICCProfileResponse
import com.betatel.esim.models.ProfileReusePolicy

class GetEUICCProfileResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetEUICCProfileResponse
        //val modelInstance = GetEUICCProfileResponse()

        // to test the property `iccid` - Integrated Circuit Card Identifier
        should("test iccid") {
            // uncomment below to test the property
            //modelInstance.iccid shouldBe ("TODO")
        }

        // to test the property `imsi` - International Mobile Subscriber Identity
        should("test imsi") {
            // uncomment below to test the property
            //modelInstance.imsi shouldBe ("TODO")
        }

        // to test the property `state` - Current state of the eUICC profile
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `lastOperationDate` - Unix timestamp of last operation
        should("test lastOperationDate") {
            // uncomment below to test the property
            //modelInstance.lastOperationDate shouldBe ("TODO")
        }

        // to test the property `activationCode` - LPA activation code for eSIM provisioning
        should("test activationCode") {
            // uncomment below to test the property
            //modelInstance.activationCode shouldBe ("TODO")
        }

        // to test the property `reuseRemainingCount` - Number of remaining profile reuses
        should("test reuseRemainingCount") {
            // uncomment below to test the property
            //modelInstance.reuseRemainingCount shouldBe ("TODO")
        }

        // to test the property `reuseEnabled` - Whether profile reuse is enabled
        should("test reuseEnabled") {
            // uncomment below to test the property
            //modelInstance.reuseEnabled shouldBe ("TODO")
        }

        // to test the property `profileReusePolicy`
        should("test profileReusePolicy") {
            // uncomment below to test the property
            //modelInstance.profileReusePolicy shouldBe ("TODO")
        }

        // to test the property `releaseDate` - Unix timestamp of profile release
        should("test releaseDate") {
            // uncomment below to test the property
            //modelInstance.releaseDate shouldBe ("TODO")
        }

        // to test the property `ccRequired` - Whether confirmation code is required
        should("test ccRequired") {
            // uncomment below to test the property
            //modelInstance.ccRequired shouldBe ("TODO")
        }

        // to test the property `ccRetries` - Number of confirmation code retries
        should("test ccRetries") {
            // uncomment below to test the property
            //modelInstance.ccRetries shouldBe ("TODO")
        }

    }
}
