/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.GetInventoriesResponse
import com.betatel.esim.models.Inventory

class GetInventoriesResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetInventoriesResponse
        //val modelInstance = GetInventoriesResponse()

        // to test the property `total` - Total number of inventories available in the system
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `count` - Number of inventories returned in this response
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `offset` - Number of inventories skipped
        should("test offset") {
            // uncomment below to test the property
            //modelInstance.offset shouldBe ("TODO")
        }

        // to test the property `inventories` - Array of inventory objects
        should("test inventories") {
            // uncomment below to test the property
            //modelInstance.inventories shouldBe ("TODO")
        }

    }
}
