/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.GetPackagesResponse
import com.betatel.esim.models.Package

class GetPackagesResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetPackagesResponse
        //val modelInstance = GetPackagesResponse()

        // to test the property `total` - Total number of packages available
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `count` - Number of items returned in this response
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `offset` - Number of items skipped
        should("test offset") {
            // uncomment below to test the property
            //modelInstance.offset shouldBe ("TODO")
        }

        // to test the property `packages` - Array of package objects
        should("test packages") {
            // uncomment below to test the property
            //modelInstance.packages shouldBe ("TODO")
        }

    }
}
