/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.GetPackageTemplatesResponse
import com.betatel.esim.models.PackageTemplate

class GetPackageTemplatesResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetPackageTemplatesResponse
        //val modelInstance = GetPackageTemplatesResponse()

        // to test the property `total` - Total number of package templates available
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `count` - Number of items returned in this response
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `offset` - Number of items skipped
        should("test offset") {
            // uncomment below to test the property
            //modelInstance.offset shouldBe ("TODO")
        }

        // to test the property `packageTemplates` - Array of package template objects
        should("test packageTemplates") {
            // uncomment below to test the property
            //modelInstance.packageTemplates shouldBe ("TODO")
        }

    }
}
