/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.IMSI

class IMSITest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IMSI
        //val modelInstance = IMSI()

        // to test the property `sponsorId` - Sponsor identifier
        should("test sponsorId") {
            // uncomment below to test the property
            //modelInstance.sponsorId shouldBe ("TODO")
        }

        // to test the property `imsi` - International Mobile Subscriber Identity
        should("test imsi") {
            // uncomment below to test the property
            //modelInstance.imsi shouldBe ("TODO")
        }

    }
}
