/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.Inventory

class InventoryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Inventory
        //val modelInstance = Inventory()

        // to test the property `id` - Unique inventory identifier
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - Inventory name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `createdDate` - Unix timestamp of creation date
        should("test createdDate") {
            // uncomment below to test the property
            //modelInstance.createdDate shouldBe ("TODO")
        }

        // to test the property `modifiedDate` - Unix timestamp of last modification
        should("test modifiedDate") {
            // uncomment below to test the property
            //modelInstance.modifiedDate shouldBe ("TODO")
        }

        // to test the property `company` - Company ID that owns this inventory
        should("test company") {
            // uncomment below to test the property
            //modelInstance.company shouldBe ("TODO")
        }

        // to test the property `status` - Current inventory status
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `note` - Optional notes about the inventory
        should("test note") {
            // uncomment below to test the property
            //modelInstance.note shouldBe ("TODO")
        }

        // to test the property `deletedDate` - Unix timestamp of deletion (0 if not deleted)
        should("test deletedDate") {
            // uncomment below to test the property
            //modelInstance.deletedDate shouldBe ("TODO")
        }

        // to test the property `parentInventory` - Parent inventory ID (0 if root inventory)
        should("test parentInventory") {
            // uncomment below to test the property
            //modelInstance.parentInventory shouldBe ("TODO")
        }

        // to test the property `deactivatedDate` - Unix timestamp of deactivation (0 if active)
        should("test deactivatedDate") {
            // uncomment below to test the property
            //modelInstance.deactivatedDate shouldBe ("TODO")
        }

        // to test the property `wallet` - Associated wallet ID
        should("test wallet") {
            // uncomment below to test the property
            //modelInstance.wallet shouldBe ("TODO")
        }

        // to test the property `whitelist` - Whitelist configuration ID
        should("test whitelist") {
            // uncomment below to test the property
            //modelInstance.whitelist shouldBe ("TODO")
        }

    }
}
