/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.ModifyPCRProfileRequestData

class ModifyPCRProfileRequestDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ModifyPCRProfileRequestData
        //val modelInstance = ModifyPCRProfileRequestData()

        // to test the property `state` - Desired state of the data profile (required when data object is provided)
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `activeThrottling` - Desired throttling speed configuration
        should("test activeThrottling") {
            // uncomment below to test the property
            //modelInstance.activeThrottling shouldBe ("TODO")
        }

    }
}
