/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.ModifyPCRProfileRequest
import com.betatel.esim.models.ModifyPCRProfileRequestData
import com.betatel.esim.models.ModifyPCRProfileRequestSms
import com.betatel.esim.models.ModifyPCRProfileRequestVoice

class ModifyPCRProfileRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ModifyPCRProfileRequest
        //val modelInstance = ModifyPCRProfileRequest()

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `voice`
        should("test voice") {
            // uncomment below to test the property
            //modelInstance.voice shouldBe ("TODO")
        }

        // to test the property `sms`
        should("test sms") {
            // uncomment below to test the property
            //modelInstance.sms shouldBe ("TODO")
        }

        // to test the property `walletMode` - Desired mode of wallet usage
        should("test walletMode") {
            // uncomment below to test the property
            //modelInstance.walletMode shouldBe ("TODO")
        }

        // to test the property `routePolicy` - Route policy for network signal handling
        should("test routePolicy") {
            // uncomment below to test the property
            //modelInstance.routePolicy shouldBe ("TODO")
        }

    }
}
