/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.ModifyPCRProfileRequestVoice

class ModifyPCRProfileRequestVoiceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ModifyPCRProfileRequestVoice
        //val modelInstance = ModifyPCRProfileRequestVoice()

        // to test the property `state` - Desired state of the voice service profile (required when voice object is provided)
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

    }
}
