/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.Package

class PackageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Package
        //val modelInstance = Package()

        // to test the property `id` - Unique package identifier
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `sim` - SIM ICCID associated with this package
        should("test sim") {
            // uncomment below to test the property
            //modelInstance.sim shouldBe ("TODO")
        }

        // to test the property `packageTemplate` - Package template ID
        should("test packageTemplate") {
            // uncomment below to test the property
            //modelInstance.packageTemplate shouldBe ("TODO")
        }

        // to test the property `status` - Current package status
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `activationDate` - Unix timestamp when package was activated
        should("test activationDate") {
            // uncomment below to test the property
            //modelInstance.activationDate shouldBe ("TODO")
        }

        // to test the property `terminationDate` - Unix timestamp when package was terminated
        should("test terminationDate") {
            // uncomment below to test the property
            //modelInstance.terminationDate shouldBe ("TODO")
        }

        // to test the property `timeAllowance` - Time allowance in seconds
        should("test timeAllowance") {
            // uncomment below to test the property
            //modelInstance.timeAllowance shouldBe ("TODO")
        }

    }
}
