/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.PackageTemplate
import com.betatel.esim.models.TimeAllowance

class PackageTemplateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PackageTemplate
        //val modelInstance = PackageTemplate()

        // to test the property `id` - Unique package template identifier
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - Package template name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `supportedCountries` - List of supported country ISO codes
        should("test supportedCountries") {
            // uncomment below to test the property
            //modelInstance.supportedCountries shouldBe ("TODO")
        }

        // to test the property `dataUsageAllowance` - Data allowance in bytes
        should("test dataUsageAllowance") {
            // uncomment below to test the property
            //modelInstance.dataUsageAllowance shouldBe ("TODO")
        }

        // to test the property `activationType` - Type of activation
        should("test activationType") {
            // uncomment below to test the property
            //modelInstance.activationType shouldBe ("TODO")
        }

        // to test the property `createdDate` - Unix timestamp of creation
        should("test createdDate") {
            // uncomment below to test the property
            //modelInstance.createdDate shouldBe ("TODO")
        }

        // to test the property `modifiedDate` - Unix timestamp of last modification
        should("test modifiedDate") {
            // uncomment below to test the property
            //modelInstance.modifiedDate shouldBe ("TODO")
        }

        // to test the property `timeAllowance`
        should("test timeAllowance") {
            // uncomment below to test the property
            //modelInstance.timeAllowance shouldBe ("TODO")
        }

        // to test the property `status` - Template status
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `trafficPolicy` - Traffic policy identifier
        should("test trafficPolicy") {
            // uncomment below to test the property
            //modelInstance.trafficPolicy shouldBe ("TODO")
        }

        // to test the property `voiceUsageAllowance` - Voice allowance in minutes
        should("test voiceUsageAllowance") {
            // uncomment below to test the property
            //modelInstance.voiceUsageAllowance shouldBe ("TODO")
        }

        // to test the property `smsUsageAllowance` - SMS allowance count
        should("test smsUsageAllowance") {
            // uncomment below to test the property
            //modelInstance.smsUsageAllowance shouldBe ("TODO")
        }

        // to test the property `activationTimeAllowance` - Time allowance for activation in seconds
        should("test activationTimeAllowance") {
            // uncomment below to test the property
            //modelInstance.activationTimeAllowance shouldBe ("TODO")
        }

        // to test the property `earliestActivationDate` - Unix timestamp of earliest activation date
        should("test earliestActivationDate") {
            // uncomment below to test the property
            //modelInstance.earliestActivationDate shouldBe ("TODO")
        }

        // to test the property `earliestAvailableDate` - Unix timestamp of earliest availability
        should("test earliestAvailableDate") {
            // uncomment below to test the property
            //modelInstance.earliestAvailableDate shouldBe ("TODO")
        }

        // to test the property `latestAvailableDate` - Unix timestamp of latest availability
        should("test latestAvailableDate") {
            // uncomment below to test the property
            //modelInstance.latestAvailableDate shouldBe ("TODO")
        }

        // to test the property `notes` - Additional notes about the template
        should("test notes") {
            // uncomment below to test the property
            //modelInstance.notes shouldBe ("TODO")
        }

        // to test the property `deactivatedDate` - Unix timestamp of deactivation (0 if active)
        should("test deactivatedDate") {
            // uncomment below to test the property
            //modelInstance.deactivatedDate shouldBe ("TODO")
        }

        // to test the property `apn` - Access Point Name
        should("test apn") {
            // uncomment below to test the property
            //modelInstance.apn shouldBe ("TODO")
        }

    }
}
