/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.ProfileReusePolicy

class ProfileReusePolicyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProfileReusePolicy
        //val modelInstance = ProfileReusePolicy()

        // to test the property `reuseType` - Type of profile reuse policy
        should("test reuseType") {
            // uncomment below to test the property
            //modelInstance.reuseType shouldBe ("TODO")
        }

        // to test the property `maxCount` - Maximum number of reuses allowed
        should("test maxCount") {
            // uncomment below to test the property
            //modelInstance.maxCount shouldBe ("TODO")
        }

    }
}
