/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.StatusResponse

class StatusResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StatusResponse
        //val modelInstance = StatusResponse()

        // to test the property `status` - Current status of the API
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `version` - API version
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `uptime` - Service uptime in seconds
        should("test uptime") {
            // uncomment below to test the property
            //modelInstance.uptime shouldBe ("TODO")
        }

    }
}
