/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.betatel.esim.models.TimeAllowance

class TimeAllowanceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TimeAllowance
        //val modelInstance = TimeAllowance()

        // to test the property `unit` - Time unit for allowance
        should("test unit") {
            // uncomment below to test the property
            //modelInstance.unit shouldBe ("TODO")
        }

        // to test the property `duration` - Duration in specified units
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

    }
}
