/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Full country name
 * @param iso2 ISO 3166-1 alpha-2 country code
 * @param iso3 ISO 3166-1 alpha-3 country code
 */


data class Country (

    /* Full country name */
    @Json(name = "name")
    val name: kotlin.String,

    /* ISO 3166-1 alpha-2 country code */
    @Json(name = "iso2")
    val iso2: kotlin.String,

    /* ISO 3166-1 alpha-3 country code */
    @Json(name = "iso3")
    val iso3: kotlin.String

) {


}

