/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sim The ICCID of the SIM card
 * @param packageTemplate The package template ID
 * @param timeAllowance Optional time allowance in seconds
 */


data class CreatePackageRequest (

    /* The ICCID of the SIM card */
    @Json(name = "sim")
    val sim: kotlin.String,

    /* The package template ID */
    @Json(name = "package_template")
    val packageTemplate: kotlin.Int,

    /* Optional time allowance in seconds */
    @Json(name = "time_allowance")
    val timeAllowance: kotlin.Long? = null

) {


}

