/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import com.betatel.esim.models.TimeAllowance

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Package template information
 *
 * @param id Template ID
 * @param name Template name
 * @param voiceUsageAllowance Voice allowance in minutes
 * @param dataUsageAllowance Data allowance in bytes
 * @param smsUsageAllowance SMS allowance count
 * @param timeAllowance 
 * @param activationTimeAllowance Time allowance for activation in seconds
 */


data class CreatePackageResponsePackageTemplate (

    /* Template ID */
    @Json(name = "id")
    val id: kotlin.Int,

    /* Template name */
    @Json(name = "name")
    val name: kotlin.String,

    /* Voice allowance in minutes */
    @Json(name = "voice_usage_allowance")
    val voiceUsageAllowance: kotlin.Int,

    /* Data allowance in bytes */
    @Json(name = "data_usage_allowance")
    val dataUsageAllowance: kotlin.Int,

    /* SMS allowance count */
    @Json(name = "sms_usage_allowance")
    val smsUsageAllowance: kotlin.Int,

    @Json(name = "time_allowance")
    val timeAllowance: TimeAllowance,

    /* Time allowance for activation in seconds */
    @Json(name = "activation_time_allowance")
    val activationTimeAllowance: kotlin.Int

) {


}

