/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import com.betatel.esim.models.TimeAllowance

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Package template name
 * @param supportedCountries Array of supported country ISO3 codes
 * @param activationType Package activation type
 * @param dataUsageAllowance Data allowance in bytes
 * @param timeAllowance 
 * @param activationTimeAllowance Time allowance for activation in seconds
 * @param earliestAvailableDate Unix timestamp for earliest availability
 * @param latestAvailableDate Unix timestamp for latest availability
 * @param inventory Inventory ID to associate the template with
 */


data class CreatePackageTemplateRequest (

    /* Package template name */
    @Json(name = "name")
    val name: kotlin.String,

    /* Array of supported country ISO3 codes */
    @Json(name = "supported_countries")
    val supportedCountries: kotlin.collections.List<kotlin.String>,

    /* Package activation type */
    @Json(name = "activation_type")
    val activationType: CreatePackageTemplateRequest.ActivationType,

    /* Data allowance in bytes */
    @Json(name = "data_usage_allowance")
    val dataUsageAllowance: kotlin.Long,

    @Json(name = "time_allowance")
    val timeAllowance: TimeAllowance,

    /* Time allowance for activation in seconds */
    @Json(name = "activation_time_allowance")
    val activationTimeAllowance: kotlin.Long,

    /* Unix timestamp for earliest availability */
    @Json(name = "earliest_available_date")
    val earliestAvailableDate: kotlin.Long,

    /* Unix timestamp for latest availability */
    @Json(name = "latest_available_date")
    val latestAvailableDate: kotlin.Long,

    /* Inventory ID to associate the template with */
    @Json(name = "inventory")
    val inventory: kotlin.Int

) {

    /**
     * Package activation type
     *
     * Values: AUTO,MANUAL
     */
    @JsonClass(generateAdapter = false)
    enum class ActivationType(val value: kotlin.String) {
        @Json(name = "AUTO") AUTO("AUTO"),
        @Json(name = "MANUAL") MANUAL("MANUAL");
    }

}

