/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import com.betatel.esim.models.CreatePackageResponsePackageTemplate

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Created package ID
 * @param sim SIM ICCID
 * @param createdDate Unix timestamp of package creation
 * @param expiryDate Unix timestamp of package expiry
 * @param activatedDate Unix timestamp when package was activated (0 if not activated)
 * @param terminatedDate Unix timestamp when package was terminated (0 if not terminated)
 * @param windowActivationStart Unix timestamp of activation window start
 * @param windowActivationEnd Unix timestamp of activation window end
 * @param status Current package status
 * @param voiceUsageRemaining Remaining voice minutes
 * @param dataUsageRemaining Remaining data in bytes
 * @param smsUsageRemaining Remaining SMS count
 * @param timeAllowance Time allowance in seconds
 * @param packageTemplate 
 * @param apn Access Point Name
 */


data class CreatePackageResponse (

    /* Created package ID */
    @Json(name = "id")
    val id: kotlin.String,

    /* SIM ICCID */
    @Json(name = "sim")
    val sim: kotlin.String,

    /* Unix timestamp of package creation */
    @Json(name = "created_date")
    val createdDate: kotlin.Long,

    /* Unix timestamp of package expiry */
    @Json(name = "expiry_date")
    val expiryDate: kotlin.Long,

    /* Unix timestamp when package was activated (0 if not activated) */
    @Json(name = "activated_date")
    val activatedDate: kotlin.Long? = null,

    /* Unix timestamp when package was terminated (0 if not terminated) */
    @Json(name = "terminated_date")
    val terminatedDate: kotlin.Long? = null,

    /* Unix timestamp of activation window start */
    @Json(name = "window_activation_start")
    val windowActivationStart: kotlin.Long,

    /* Unix timestamp of activation window end */
    @Json(name = "window_activation_end")
    val windowActivationEnd: kotlin.Long,

    /* Current package status */
    @Json(name = "status")
    val status: CreatePackageResponse.Status,

    /* Remaining voice minutes */
    @Json(name = "voice_usage_remaining")
    val voiceUsageRemaining: kotlin.Long,

    /* Remaining data in bytes */
    @Json(name = "data_usage_remaining")
    val dataUsageRemaining: kotlin.Long,

    /* Remaining SMS count */
    @Json(name = "sms_usage_remaining")
    val smsUsageRemaining: kotlin.Long,

    /* Time allowance in seconds */
    @Json(name = "time_allowance")
    val timeAllowance: kotlin.Long,

    @Json(name = "package_template")
    val packageTemplate: CreatePackageResponsePackageTemplate,

    /* Access Point Name */
    @Json(name = "apn")
    val apn: kotlin.String? = null

) {

    /**
     * Current package status
     *
     * Values: NOT_ACTIVE,ACTIVE,SUSPENDED,TERMINATED
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "NOT_ACTIVE") NOT_ACTIVE("NOT_ACTIVE"),
        @Json(name = "ACTIVE") ACTIVE("ACTIVE"),
        @Json(name = "SUSPENDED") SUSPENDED("SUSPENDED"),
        @Json(name = "TERMINATED") TERMINATED("TERMINATED");
    }

}

