/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param message Error message
 * @param statusCode HTTP status code
 */


data class Error (

    /* Error message */
    @Json(name = "message")
    val message: kotlin.String? = null,

    /* HTTP status code */
    @Json(name = "statusCode")
    val statusCode: kotlin.Int? = null

) {


}

