/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Company identifier
 * @param name Company name
 */


data class ESIMCompany (

    /* Company identifier */
    @Json(name = "id")
    val id: kotlin.Int,

    /* Company name */
    @Json(name = "name")
    val name: kotlin.String

) {


}

