/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import com.betatel.esim.models.ESIMCompany
import com.betatel.esim.models.ESIMGroup
import com.betatel.esim.models.ESIMInventory
import com.betatel.esim.models.IMSI

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param iccid Integrated Circuit Card Identifier
 * @param simStatus Current status of the SIM
 * @param group 
 * @param inventory 
 * @param company 
 * @param createdDate Unix timestamp when SIM was created
 * @param modifiedDate Unix timestamp when SIM was modified
 * @param imsis List of associated IMSIs
 * @param mappedImsi Currently mapped IMSI
 */


data class ESIMPartial (

    /* Integrated Circuit Card Identifier */
    @Json(name = "iccid")
    val iccid: kotlin.String,

    /* Current status of the SIM */
    @Json(name = "sim_status")
    val simStatus: ESIM.SimStatus,

    @Json(name = "group")
    val group: kotlin.Int? = null,

    @Json(name = "inventory")
    val inventory: kotlin.Int? = null,

    @Json(name = "company")
    val company: kotlin.Int? = null,

    /* Unix timestamp when SIM was created */
    @Json(name = "created_date")
    val createdDate: kotlin.Long? = null,

    /* Unix timestamp when SIM was modified */
    @Json(name = "modified_date")
    val modifiedDate: kotlin.Long? = null,

    /* List of associated IMSIs */
    @Json(name = "imsis")
    val imsis: kotlin.collections.List<IMSI>? = null,

    /* Currently mapped IMSI */
    @Json(name = "mapped_imsi")
    val mappedImsi: kotlin.Long? = null

) {

    /**
     * Current status of the SIM
     *
     * Values: WAITING_FOR_ASSIGNMENT,ASSIGNED,ACTIVE,SUSPENDED,TERMINATED, IN_SERVICE, PRE_SERVICE
     */
    @JsonClass(generateAdapter = false)
    enum class SimStatus(val value: kotlin.String) {
        @Json(name = "WAITING_FOR_ASSIGNMENT") WAITING_FOR_ASSIGNMENT("WAITING_FOR_ASSIGNMENT"),
        @Json(name = "IN_SERVICE") IN_SERVICE("IN_SERVICE"),
        @Json(name = "PRE_SERVICE") PRE_SERVICE("PRE_SERVICE"),
        @Json(name = "TERMINATED") TERMINATED("TERMINATED");
    }

}

