/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import com.betatel.esim.models.ESIMCompany
import com.betatel.esim.models.ESIMGroup
import com.betatel.esim.models.ESIMInventory
import com.betatel.esim.models.IMSI

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param iccid Integrated Circuit Card Identifier
 * @param simStatus Current status of the SIM
 * @param group 
 * @param inventory 
 * @param company 
 * @param provisionedDate Unix timestamp when SIM was provisioned
 * @param terminatedDate Unix timestamp when SIM was terminated (0 if active)
 * @param imsis List of associated IMSIs
 * @param mappedImsi Currently mapped IMSI
 */


data class ESIM (

    /* Integrated Circuit Card Identifier */
    @Json(name = "iccid")
    val iccid: kotlin.String,

    /* Current status of the SIM */
    @Json(name = "sim_status")
    val simStatus: ESIM.SimStatus,

    @Json(name = "group")
    val group: ESIMGroup? = null,

    @Json(name = "inventory")
    val inventory: ESIMInventory? = null,

    @Json(name = "company")
    val company: ESIMCompany? = null,

    /* Unix timestamp when SIM was provisioned */
    @Json(name = "provisioned_date")
    val provisionedDate: kotlin.Int? = null,

    /* Unix timestamp when SIM was terminated (0 if active) */
    @Json(name = "terminated_date")
    val terminatedDate: kotlin.Int? = null,

    /* List of associated IMSIs */
    @Json(name = "imsis")
    val imsis: kotlin.collections.List<IMSI>? = null,

    /* Currently mapped IMSI */
    @Json(name = "mapped_imsi")
    val mappedImsi: kotlin.Int? = null

) {

    /**
     * Current status of the SIM
     *
     * Values: WAITING_FOR_ASSIGNMENT,ASSIGNED,ACTIVE,SUSPENDED,TERMINATED
     */
    @JsonClass(generateAdapter = false)
    enum class SimStatus(val value: kotlin.String) {
        @Json(name = "WAITING_FOR_ASSIGNMENT") WAITING_FOR_ASSIGNMENT("WAITING_FOR_ASSIGNMENT"),
        @Json(name = "ASSIGNED") ASSIGNED("ASSIGNED"),
        @Json(name = "ACTIVE") ACTIVE("ACTIVE"),
        @Json(name = "SUSPENDED") SUSPENDED("SUSPENDED"),
        @Json(name = "TERMINATED") TERMINATED("TERMINATED");
    }

}

