/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import com.betatel.esim.models.Country

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param total Total number of countries available in the system
 * @param count Number of countries returned in this response
 * @param offset Number of countries skipped
 * @param countries Array of country objects
 */


data class GetCountriesResponse (

    /* Total number of countries available in the system */
    @Json(name = "total")
    val total: kotlin.Int,

    /* Number of countries returned in this response */
    @Json(name = "count")
    val count: kotlin.Int,

    /* Number of countries skipped */
    @Json(name = "offset")
    val offset: kotlin.Int,

    /* Array of country objects */
    @Json(name = "countries")
    val countries: kotlin.collections.List<Country>

) {


}

