/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import com.betatel.esim.models.ESIM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param total Total number of eSIMs available in the system
 * @param count Number of eSIMs returned in this response
 * @param offset Number of eSIMs skipped
 * @param sims Array of eSIM objects
 */


data class GetESIMsResponse (

    /* Total number of eSIMs available in the system */
    @Json(name = "total")
    val total: kotlin.Int,

    /* Number of eSIMs returned in this response */
    @Json(name = "count")
    val count: kotlin.Int,

    /* Number of eSIMs skipped */
    @Json(name = "offset")
    val offset: kotlin.Int,

    /* Array of eSIM objects */
    @Json(name = "sims")
    val sims: kotlin.collections.List<ESIM>

) {


}

