/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import com.betatel.esim.models.ProfileReusePolicy

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param iccid Integrated Circuit Card Identifier
 * @param imsi International Mobile Subscriber Identity
 * @param state Current state of the eUICC profile
 * @param lastOperationDate Unix timestamp of last operation
 * @param activationCode LPA activation code for eSIM provisioning
 * @param reuseRemainingCount Number of remaining profile reuses
 * @param reuseEnabled Whether profile reuse is enabled
 * @param profileReusePolicy 
 * @param releaseDate Unix timestamp of profile release
 * @param ccRequired Whether confirmation code is required
 * @param ccRetries Number of confirmation code retries
 */


data class GetEUICCProfileResponse (

    /* Integrated Circuit Card Identifier */
    @Json(name = "iccid")
    val iccid: kotlin.String,

    /* International Mobile Subscriber Identity */
    @Json(name = "imsi")
    val imsi: kotlin.String,

    /* Current state of the eUICC profile */
    @Json(name = "state")
    val state: GetEUICCProfileResponse.State,

    /* Unix timestamp of last operation */
    @Json(name = "last_operation_date")
    val lastOperationDate: kotlin.Int,

    /* LPA activation code for eSIM provisioning */
    @Json(name = "activation_code")
    val activationCode: kotlin.String,

    /* Number of remaining profile reuses */
    @Json(name = "reuse_remaining_count")
    val reuseRemainingCount: kotlin.Int? = null,

    /* Whether profile reuse is enabled */
    @Json(name = "reuse_enabled")
    val reuseEnabled: kotlin.Boolean? = null,

    @Json(name = "profile_reuse_policy")
    val profileReusePolicy: ProfileReusePolicy? = null,

    /* Unix timestamp of profile release */
    @Json(name = "release_date")
    val releaseDate: kotlin.Int? = null,

    /* Whether confirmation code is required */
    @Json(name = "cc_required")
    val ccRequired: kotlin.Boolean? = null,

    /* Number of confirmation code retries */
    @Json(name = "cc_retries")
    val ccRetries: kotlin.Int? = null

) {

    /**
     * Current state of the eUICC profile
     *
     * Values: CONFIRMED,PENDING,RELEASED
     */
    @JsonClass(generateAdapter = false)
    enum class State(val value: kotlin.String) {
        @Json(name = "CONFIRMED") CONFIRMED("CONFIRMED"),
        @Json(name = "PENDING") PENDING("PENDING"),
        @Json(name = "RELEASED") RELEASED("RELEASED");
    }

}

