/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import com.betatel.esim.models.Inventory

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param total Total number of inventories available in the system
 * @param count Number of inventories returned in this response
 * @param offset Number of inventories skipped
 * @param inventories Array of inventory objects
 */


data class GetInventoriesResponse (

    /* Total number of inventories available in the system */
    @Json(name = "total")
    val total: kotlin.Int,

    /* Number of inventories returned in this response */
    @Json(name = "count")
    val count: kotlin.Int,

    /* Number of inventories skipped */
    @Json(name = "offset")
    val offset: kotlin.Int,

    /* Array of inventory objects */
    @Json(name = "inventories")
    val inventories: kotlin.collections.List<Inventory>

) {


}

