/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import com.betatel.esim.models.DataProfile
import com.betatel.esim.models.ServiceProfile

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` 
 * @param voice 
 * @param sms 
 * @param walletMode Current wallet mode
 * @param routePolicy Current route policy
 */


data class GetPCRProfileResponse (

    @Json(name = "data")
    val `data`: DataProfile,

    @Json(name = "voice")
    val voice: ServiceProfile,

    @Json(name = "sms")
    val sms: ServiceProfile,

    /* Current wallet mode */
    @Json(name = "wallet_mode")
    val walletMode: GetPCRProfileResponse.WalletMode,

    /* Current route policy */
    @Json(name = "route_policy")
    val routePolicy: kotlin.Int? = null

) {

    /**
     * Current wallet mode
     *
     * Values: GROUP,SIM
     */
    @JsonClass(generateAdapter = false)
    enum class WalletMode(val value: kotlin.String) {
        @Json(name = "GROUP") GROUP("GROUP"),
        @Json(name = "SIM") SIM("SIM");
    }

}

