/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import com.betatel.esim.models.Package

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param total Total number of packages available
 * @param count Number of items returned in this response
 * @param offset Number of items skipped
 * @param packages Array of package objects
 */


data class GetPackagesResponse (

    /* Total number of packages available */
    @Json(name = "total")
    val total: kotlin.Int,

    /* Number of items returned in this response */
    @Json(name = "count")
    val count: kotlin.Int,

    /* Number of items skipped */
    @Json(name = "offset")
    val offset: kotlin.Int,

    /* Array of package objects */
    @Json(name = "packages")
    val packages: kotlin.collections.List<Package>

) {


}

