/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import com.betatel.esim.models.PackageTemplate

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param total Total number of package templates available
 * @param count Number of items returned in this response
 * @param offset Number of items skipped
 * @param packageTemplates Array of package template objects
 */


data class GetPackageTemplatesResponse (

    /* Total number of package templates available */
    @Json(name = "total")
    val total: kotlin.Int,

    /* Number of items returned in this response */
    @Json(name = "count")
    val count: kotlin.Int,

    /* Number of items skipped */
    @Json(name = "offset")
    val offset: kotlin.Int,

    /* Array of package template objects */
    @Json(name = "package_templates")
    val packageTemplates: kotlin.collections.List<PackageTemplate>

) {


}

