/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sponsorId Sponsor identifier
 * @param imsi International Mobile Subscriber Identity
 */


data class IMSI (

    /* Sponsor identifier */
    @Json(name = "sponsor_id")
    val sponsorId: kotlin.Long,

    /* International Mobile Subscriber Identity */
    @Json(name = "imsi")
    val imsi: kotlin.Long

) {


}

