/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Unique inventory identifier
 * @param name Inventory name
 * @param createdDate Unix timestamp of creation date
 * @param modifiedDate Unix timestamp of last modification
 * @param company Company ID that owns this inventory
 * @param status Current inventory status
 * @param note Optional notes about the inventory
 * @param deletedDate Unix timestamp of deletion (0 if not deleted)
 * @param parentInventory Parent inventory ID (0 if root inventory)
 * @param deactivatedDate Unix timestamp of deactivation (0 if active)
 * @param wallet Associated wallet ID
 * @param whitelist Whitelist configuration ID
 */


data class Inventory (

    /* Unique inventory identifier */
    @Json(name = "id")
    val id: kotlin.Int,

    /* Inventory name */
    @Json(name = "name")
    val name: kotlin.String,

    /* Unix timestamp of creation date */
    @Json(name = "created_date")
    val createdDate: kotlin.Int,

    /* Unix timestamp of last modification */
    @Json(name = "modified_date")
    val modifiedDate: kotlin.Int,

    /* Company ID that owns this inventory */
    @Json(name = "company")
    val company: kotlin.Int,

    /* Current inventory status */
    @Json(name = "status")
    val status: Inventory.Status,

    /* Optional notes about the inventory */
    @Json(name = "note")
    val note: kotlin.String? = null,

    /* Unix timestamp of deletion (0 if not deleted) */
    @Json(name = "deleted_date")
    val deletedDate: kotlin.Int? = null,

    /* Parent inventory ID (0 if root inventory) */
    @Json(name = "parent_inventory")
    val parentInventory: kotlin.Int? = null,

    /* Unix timestamp of deactivation (0 if active) */
    @Json(name = "deactivated_date")
    val deactivatedDate: kotlin.Int? = null,

    /* Associated wallet ID */
    @Json(name = "wallet")
    val wallet: kotlin.Int? = null,

    /* Whitelist configuration ID */
    @Json(name = "whitelist")
    val whitelist: kotlin.Int? = null

) {

    /**
     * Current inventory status
     *
     * Values: NOT_ACTIVE,ACTIVE
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "NOT_ACTIVE") NOT_ACTIVE("NOT_ACTIVE"),
        @Json(name = "ACTIVE") ACTIVE("ACTIVE");
    }

}

