/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import com.betatel.esim.models.ModifyPCRProfileRequestData
import com.betatel.esim.models.ModifyPCRProfileRequestSms
import com.betatel.esim.models.ModifyPCRProfileRequestVoice

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` 
 * @param voice 
 * @param sms 
 * @param walletMode Desired mode of wallet usage
 * @param routePolicy Route policy for network signal handling
 */


data class ModifyPCRProfileRequest (

    @Json(name = "data")
    val `data`: ModifyPCRProfileRequestData,

    @Json(name = "voice")
    val voice: ModifyPCRProfileRequestVoice,

    @Json(name = "sms")
    val sms: ModifyPCRProfileRequestSms,

    /* Desired mode of wallet usage */
    @Json(name = "wallet_mode")
    val walletMode: ModifyPCRProfileRequest.WalletMode,

    /* Route policy for network signal handling */
    @Json(name = "route_policy")
    val routePolicy: kotlin.Int? = null

) {

    /**
     * Desired mode of wallet usage
     *
     * Values: GROUP,SIM
     */
    @JsonClass(generateAdapter = false)
    enum class WalletMode(val value: kotlin.String) {
        @Json(name = "GROUP") GROUP("GROUP"),
        @Json(name = "SIM") SIM("SIM");
    }

}

