/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param state Desired state of the voice service profile (required when voice object is provided)
 */


data class ModifyPCRProfileRequestVoice (

    /* Desired state of the voice service profile (required when voice object is provided) */
    @Json(name = "state")
    val state: ModifyPCRProfileRequestVoice.State

) {

    /**
     * Desired state of the voice service profile (required when voice object is provided)
     *
     * Values: ENABLED,DISABLED
     */
    @JsonClass(generateAdapter = false)
    enum class State(val value: kotlin.String) {
        @Json(name = "ENABLED") ENABLED("ENABLED"),
        @Json(name = "DISABLED") DISABLED("DISABLED");
    }

}

