/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param state Desired state of the data profile (required when data object is provided)
 * @param activeThrottling Desired throttling speed configuration
 */


data class ModifyPCRProfileRequestData (

    /* Desired state of the data profile (required when data object is provided) */
    @Json(name = "state")
    val state: ModifyPCRProfileRequestData.State,

    /* Desired throttling speed configuration */
    @Json(name = "active_throttling")
    val activeThrottling: ModifyPCRProfileRequestData.ActiveThrottling

) {

    /**
     * Desired state of the data profile (required when data object is provided)
     *
     * Values: ENABLED,DISABLED
     */
    @JsonClass(generateAdapter = false)
    enum class State(val value: kotlin.String) {
        @Json(name = "ENABLED") ENABLED("ENABLED"),
        @Json(name = "DISABLED") DISABLED("DISABLED");
    }
    /**
     * Desired throttling speed configuration
     *
     * Values: NO_LIMIT,SPEED_100_KBPS,SPEED_500_KBPS,SPEED_1000_KBPS,SPEED_2000_KBPS,SPEED_3000_KBPS,SPEED_5000_KBPS
     */
    @JsonClass(generateAdapter = false)
    enum class ActiveThrottling(val value: kotlin.String) {
        @Json(name = "NO_LIMIT") NO_LIMIT("NO_LIMIT"),
        @Json(name = "SPEED_100_KBPS") SPEED_100_KBPS("SPEED_100_KBPS"),
        @Json(name = "SPEED_500_KBPS") SPEED_500_KBPS("SPEED_500_KBPS"),
        @Json(name = "SPEED_1000_KBPS") SPEED_1000_KBPS("SPEED_1000_KBPS"),
        @Json(name = "SPEED_2000_KBPS") SPEED_2000_KBPS("SPEED_2000_KBPS"),
        @Json(name = "SPEED_3000_KBPS") SPEED_3000_KBPS("SPEED_3000_KBPS"),
        @Json(name = "SPEED_5000_KBPS") SPEED_5000_KBPS("SPEED_5000_KBPS");
    }

}

