/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Unique package identifier
 * @param sim SIM ICCID associated with this package
 * @param packageTemplate Package template ID
 * @param status Current package status
 * @param activationDate Unix timestamp when package was activated
 * @param terminationDate Unix timestamp when package was terminated
 * @param timeAllowance Time allowance in seconds
 */


data class Package (

    /* Unique package identifier */
    @Json(name = "id")
    val id: kotlin.String,

    /* SIM ICCID associated with this package */
    @Json(name = "sim")
    val sim: kotlin.String,

    /* Package template ID */
    @Json(name = "package_template")
    val packageTemplate: kotlin.Int,

    /* Current package status */
    @Json(name = "status")
    val status: Package.Status,

    /* Unix timestamp when package was activated */
    @Json(name = "activation_date")
    val activationDate: kotlin.Long? = null,

    /* Unix timestamp when package was terminated */
    @Json(name = "termination_date")
    val terminationDate: kotlin.Long? = null,

    /* Time allowance in seconds */
    @Json(name = "time_allowance")
    val timeAllowance: kotlin.Long? = null

) {

    /**
     * Current package status
     *
     * Values: NOT_ACTIVE,ACTIVE,SUSPENDED,TERMINATED
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "NOT_ACTIVE") NOT_ACTIVE("NOT_ACTIVE"),
        @Json(name = "ACTIVE") ACTIVE("ACTIVE"),
        @Json(name = "SUSPENDED") SUSPENDED("SUSPENDED"),
        @Json(name = "TERMINATED") TERMINATED("TERMINATED");
    }

}

