/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import com.betatel.esim.models.TimeAllowance

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Unique package template identifier
 * @param name Package template name
 * @param supportedCountries List of supported country ISO codes
 * @param dataUsageAllowance Data allowance in bytes
 * @param activationType Type of activation
 * @param createdDate Unix timestamp of creation
 * @param modifiedDate Unix timestamp of last modification
 * @param timeAllowance 
 * @param status Template status
 * @param trafficPolicy Traffic policy identifier
 * @param voiceUsageAllowance Voice allowance in minutes
 * @param smsUsageAllowance SMS allowance count
 * @param activationTimeAllowance Time allowance for activation in seconds
 * @param earliestActivationDate Unix timestamp of earliest activation date
 * @param earliestAvailableDate Unix timestamp of earliest availability
 * @param latestAvailableDate Unix timestamp of latest availability
 * @param notes Additional notes about the template
 * @param deactivatedDate Unix timestamp of deactivation (0 if active)
 * @param apn Access Point Name
 */


data class PackageTemplate (

    /* Unique package template identifier */
    @Json(name = "id")
    val id: kotlin.Int,

    /* Package template name */
    @Json(name = "name")
    val name: kotlin.String,

    /* List of supported country ISO codes */
    @Json(name = "supported_countries")
    val supportedCountries: kotlin.collections.List<kotlin.String>,

    /* Data allowance in bytes */
    @Json(name = "data_usage_allowance")
    val dataUsageAllowance: kotlin.Long,

    /* Type of activation */
    @Json(name = "activation_type")
    val activationType: PackageTemplate.ActivationType,

    /* Unix timestamp of creation */
    @Json(name = "created_date")
    val createdDate: kotlin.Long,

    /* Unix timestamp of last modification */
    @Json(name = "modified_date")
    val modifiedDate: kotlin.Long,

    @Json(name = "time_allowance")
    val timeAllowance: TimeAllowance,

    /* Template status */
    @Json(name = "status")
    val status: PackageTemplate.Status,

    /* Traffic policy identifier */
    @Json(name = "traffic_policy")
    val trafficPolicy: kotlin.Int? = null,

    /* Voice allowance in minutes */
    @Json(name = "voice_usage_allowance")
    val voiceUsageAllowance: kotlin.Long? = null,

    /* SMS allowance count */
    @Json(name = "sms_usage_allowance")
    val smsUsageAllowance: kotlin.Long? = null,

    /* Time allowance for activation in seconds */
    @Json(name = "activation_time_allowance")
    val activationTimeAllowance: kotlin.Long? = null,

    /* Unix timestamp of earliest activation date */
    @Json(name = "earliest_activation_date")
    val earliestActivationDate: kotlin.Long? = null,

    /* Unix timestamp of earliest availability */
    @Json(name = "earliest_available_date")
    val earliestAvailableDate: kotlin.Long? = null,

    /* Unix timestamp of latest availability */
    @Json(name = "latest_available_date")
    val latestAvailableDate: kotlin.Long? = null,

    /* Additional notes about the template */
    @Json(name = "notes")
    val notes: kotlin.String? = null,

    /* Unix timestamp of deactivation (0 if active) */
    @Json(name = "deactivated_date")
    val deactivatedDate: kotlin.Long? = null,

    /* Access Point Name */
    @Json(name = "apn")
    val apn: kotlin.String? = null

) {

    /**
     * Type of activation
     *
     * Values: AUTO,MANUAL
     */
    @JsonClass(generateAdapter = false)
    enum class ActivationType(val value: kotlin.String) {
        @Json(name = "AUTO") AUTO("AUTO"),
        @Json(name = "MANUAL") MANUAL("MANUAL");
    }
    /**
     * Template status
     *
     * Values: Active,DeActivated
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "Active") Active("Active"),
        @Json(name = "De-activated") DeActivated("De-activated");
    }

}

