/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param count Number of items to return
 * @param offset Number of items to skip
 */


data class PaginationParams (

    /* Number of items to return */
    @Json(name = "count")
    val count: kotlin.Int? = 100,

    /* Number of items to skip */
    @Json(name = "offset")
    val offset: kotlin.Int? = 0

) {


}

