/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param reuseType Type of profile reuse policy
 * @param maxCount Maximum number of reuses allowed
 */


data class ProfileReusePolicy (

    /* Type of profile reuse policy */
    @Json(name = "reuse_type")
    val reuseType: ProfileReusePolicy.ReuseType,

    /* Maximum number of reuses allowed */
    @Json(name = "max_count")
    val maxCount: kotlin.Int

) {

    /**
     * Type of profile reuse policy
     *
     * Values: NEW_EID_MID,NEW_EID,SAME_EID
     */
    @JsonClass(generateAdapter = false)
    enum class ReuseType(val value: kotlin.String) {
        @Json(name = "NEW_EID_MID") NEW_EID_MID("NEW_EID_MID"),
        @Json(name = "NEW_EID") NEW_EID("NEW_EID"),
        @Json(name = "SAME_EID") SAME_EID("SAME_EID"),
        @Json(name = "SAME_EID_MID") SAME_EID_MID("SAME_EID_MID");
    }

}

