/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status Current status of the API
 * @param version API version
 * @param uptime Service uptime in seconds
 */


data class StatusResponse (

    /* Current status of the API */
    @Json(name = "status")
    val status: StatusResponse.Status,

    /* API version */
    @Json(name = "version")
    val version: kotlin.String,

    /* Service uptime in seconds */
    @Json(name = "uptime")
    val uptime: kotlin.Int? = null

) {

    /**
     * Current status of the API
     *
     * Values: ok,error
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "ok") ok("ok"),
        @Json(name = "error") error("error");
    }

}

