/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param unit Time unit for allowance
 * @param duration Duration in specified units
 */


data class TimeAllowance (

    /* Time unit for allowance */
    @Json(name = "unit")
    val unit: TimeAllowance.Unit,

    /* Duration in specified units */
    @Json(name = "duration")
    val duration: kotlin.Int

) {

    /**
     * Time unit for allowance
     *
     * Values: SECOND,MINUTE,HOUR,DAY,WEEK,MONTH,CALENDAR_MONTH,YEAR
     */
    @JsonClass(generateAdapter = false)
    enum class Unit(val value: kotlin.String) {
        @Json(name = "SECOND") SECOND("SECOND"),
        @Json(name = "MINUTE") MINUTE("MINUTE"),
        @Json(name = "HOUR") HOUR("HOUR"),
        @Json(name = "DAY") DAY("DAY"),
        @Json(name = "WEEK") WEEK("WEEK"),
        @Json(name = "MONTH") MONTH("MONTH"),
        @Json(name = "CALENDAR_MONTH") CALENDAR_MONTH("CALENDAR_MONTH"),
        @Json(name = "YEAR") YEAR("YEAR");
    }

}

