/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param group Group ID if wallet belongs to a group
 * @param inventory Inventory ID if wallet belongs to an inventory
 * @param sim SIM ICCID if wallet belongs to a SIM
 */


data class WalletOwner (

    /* Group ID if wallet belongs to a group */
    @Json(name = "group")
    val group: kotlin.Int? = null,

    /* Inventory ID if wallet belongs to an inventory */
    @Json(name = "inventory")
    val inventory: kotlin.Int? = null,

    /* SIM ICCID if wallet belongs to a SIM */
    @Json(name = "sim")
    val sim: kotlin.String? = null

) {


}