/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.models

import com.betatel.esim.models.WalletOwner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Wallet identifier
 * @param owner 
 * @param balance Current wallet balance
 * @param overdraft Overdraft limit
 * @param walletType Type of wallet
 */


data class Wallet (

    /* Wallet identifier */
    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "owner")
    val owner: WalletOwner,

    /* Current wallet balance */
    @Json(name = "balance")
    val balance: kotlin.Long,

    /* Overdraft limit */
    @Json(name = "overdraft")
    val overdraft: kotlin.Long,

    /* Type of wallet */
    @Json(name = "wallet_type")
    val walletType: Wallet.WalletType

) {

    /**
     * Type of wallet
     *
     * Values: GROUP,INVENTORY,SIM
     */
    @JsonClass(generateAdapter = false)
    enum class WalletType(val value: kotlin.String) {
        @Json(name = "GROUP") GROUP("GROUP"),
        @Json(name = "INVENTORY") INVENTORY("INVENTORY"),
        @Json(name = "SIM") SIM("SIM");
    }

}