/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.betatel.esim.models.CreatePackageTemplateRequest
import com.betatel.esim.models.CreatePackageTemplateResponse
import com.betatel.esim.models.Error
import com.betatel.esim.models.GetPackageTemplatesResponse
import com.betatel.esim.models.PackageTemplate

import com.squareup.moshi.Json

import com.betatel.esim.infrastructure.ApiClient
import com.betatel.esim.infrastructure.ApiResponse
import com.betatel.esim.infrastructure.ClientException
import com.betatel.esim.infrastructure.ClientError
import com.betatel.esim.infrastructure.ServerException
import com.betatel.esim.infrastructure.ServerError
import com.betatel.esim.infrastructure.MultiValueMap
import com.betatel.esim.infrastructure.PartConfig
import com.betatel.esim.infrastructure.RequestConfig
import com.betatel.esim.infrastructure.RequestMethod
import com.betatel.esim.infrastructure.ResponseType
import com.betatel.esim.infrastructure.Success
import com.betatel.esim.infrastructure.toMultiValue

class PCRApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://esim.betatel.com/api/v1/esim")
        }
    }

    /**
     * POST /package-templates
     * Create a new package template
     * Creates a new package template with specified data, time, and activation configurations
     * @param createPackageTemplateRequest 
     * @return CreatePackageTemplateResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createPackageTemplate(createPackageTemplateRequest: CreatePackageTemplateRequest) : CreatePackageTemplateResponse {
        val localVarResponse = createPackageTemplateWithHttpInfo(createPackageTemplateRequest = createPackageTemplateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreatePackageTemplateResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /package-templates
     * Create a new package template
     * Creates a new package template with specified data, time, and activation configurations
     * @param createPackageTemplateRequest 
     * @return ApiResponse<CreatePackageTemplateResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createPackageTemplateWithHttpInfo(createPackageTemplateRequest: CreatePackageTemplateRequest) : ApiResponse<CreatePackageTemplateResponse?> {
        val localVariableConfig = createPackageTemplateRequestConfig(createPackageTemplateRequest = createPackageTemplateRequest)

        return request<CreatePackageTemplateRequest, CreatePackageTemplateResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createPackageTemplate
     *
     * @param createPackageTemplateRequest 
     * @return RequestConfig
     */
    fun createPackageTemplateRequestConfig(createPackageTemplateRequest: CreatePackageTemplateRequest) : RequestConfig<CreatePackageTemplateRequest> {
        val localVariableBody = createPackageTemplateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/package-templates",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /package-templates/{id}
     * Get package template by ID
     * Returns detailed information about a specific package template
     * @param id Package template ID
     * @return PackageTemplate
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getPackageTemplate(id: kotlin.Int) : PackageTemplate {
        val localVarResponse = getPackageTemplateWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PackageTemplate
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /package-templates/{id}
     * Get package template by ID
     * Returns detailed information about a specific package template
     * @param id Package template ID
     * @return ApiResponse<PackageTemplate?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getPackageTemplateWithHttpInfo(id: kotlin.Int) : ApiResponse<PackageTemplate?> {
        val localVariableConfig = getPackageTemplateRequestConfig(id = id)

        return request<Unit, PackageTemplate>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getPackageTemplate
     *
     * @param id Package template ID
     * @return RequestConfig
     */
    fun getPackageTemplateRequestConfig(id: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/package-templates/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /package-templates
     * Get list of package templates
     * Returns a paginated list of all available package templates with optional filtering
     * @param count Number of items to return (optional, default to 100)
     * @param offset Number of items to skip (optional, default to 0)
     * @param inventory Filter by inventory ID (optional) (optional)
     * @return GetPackageTemplatesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getPackageTemplates(count: kotlin.Int? = 100, offset: kotlin.Int? = 0, inventory: kotlin.Int? = null) : GetPackageTemplatesResponse {
        val localVarResponse = getPackageTemplatesWithHttpInfo(count = count, offset = offset, inventory = inventory)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetPackageTemplatesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /package-templates
     * Get list of package templates
     * Returns a paginated list of all available package templates with optional filtering
     * @param count Number of items to return (optional, default to 100)
     * @param offset Number of items to skip (optional, default to 0)
     * @param inventory Filter by inventory ID (optional) (optional)
     * @return ApiResponse<GetPackageTemplatesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getPackageTemplatesWithHttpInfo(count: kotlin.Int?, offset: kotlin.Int?, inventory: kotlin.Int?) : ApiResponse<GetPackageTemplatesResponse?> {
        val localVariableConfig = getPackageTemplatesRequestConfig(count = count, offset = offset, inventory = inventory)

        return request<Unit, GetPackageTemplatesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getPackageTemplates
     *
     * @param count Number of items to return (optional, default to 100)
     * @param offset Number of items to skip (optional, default to 0)
     * @param inventory Filter by inventory ID (optional) (optional)
     * @return RequestConfig
     */
    fun getPackageTemplatesRequestConfig(count: kotlin.Int?, offset: kotlin.Int?, inventory: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (count != null) {
                    put("count", listOf(count.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
                if (inventory != null) {
                    put("inventory", listOf(inventory.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/package-templates",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
