/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.betatel.esim.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.betatel.esim.models.Error
import com.betatel.esim.models.StatusResponse

import com.squareup.moshi.Json

import com.betatel.esim.infrastructure.ApiClient
import com.betatel.esim.infrastructure.ApiResponse
import com.betatel.esim.infrastructure.ClientException
import com.betatel.esim.infrastructure.ClientError
import com.betatel.esim.infrastructure.ServerException
import com.betatel.esim.infrastructure.ServerError
import com.betatel.esim.infrastructure.MultiValueMap
import com.betatel.esim.infrastructure.PartConfig
import com.betatel.esim.infrastructure.RequestConfig
import com.betatel.esim.infrastructure.RequestMethod
import com.betatel.esim.infrastructure.ResponseType
import com.betatel.esim.infrastructure.Success
import com.betatel.esim.infrastructure.toMultiValue

class SystemApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://esim.betatel.com/api/v1/esim")
        }
    }

    /**
     * GET /api/v1/status
     * Check API status
     * Returns the current status of the eSIM API service, including version information and health check
     * @return StatusResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getStatus() : StatusResponse {
        val localVarResponse = getStatusWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as StatusResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/status
     * Check API status
     * Returns the current status of the eSIM API service, including version information and health check
     * @return ApiResponse<StatusResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getStatusWithHttpInfo() : ApiResponse<StatusResponse?> {
        val localVariableConfig = getStatusRequestConfig()

        return request<Unit, StatusResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getStatus
     *
     * @return RequestConfig
     */
    fun getStatusRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/status",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
